# Generated by Django 6.1.1 on 2026-09-30 03:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CeramicShape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=170, unique=True)),
                ('category_label', models.CharField(default='Ceramic Vessel', max_length=80)),
                ('description', models.TextField()),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('dimensions', models.CharField(default='10"H x 7"W', max_length=100)),
                ('shape_code', models.CharField(help_text='Key used by the interactive canvas renderer: pleated_lamp, fluted_vase, donut_flask, desk_cup, tea_bowl', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GlazeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hex_color', models.CharField(help_text='e.g. #F2EDE4', max_length=20)),
                ('accent_color', models.CharField(default='#DFD5C6', help_text='Secondary gradient / shade tone', max_length=20)),
                ('texture_type', models.CharField(choices=[('speckled', 'Speckled Mineral Sand'), ('satin_matte', 'Smooth Satin Matte'), ('ribbed_tactile', 'Tactile Ribbed Flute'), ('terracotta_raw', 'Raw Fired Terracotta'), ('crackle_celadon', 'Crackle Glaze Celadon')], default='speckled', max_length=50)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('price_modifier', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('badge', models.CharField(blank=True, help_text='e.g. Signature Glaze, Most Loved', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomCreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=60)),
                ('finish_texture', models.CharField(default='speckled', max_length=50)),
                ('lamp_stand_color', models.CharField(choices=[('white', 'Alabaster Architectural Iron'), ('brass', 'Warm Brushed Brass'), ('matte_black', 'Forged Matte Black')], default='white', max_length=50)),
                ('engraving_text', models.CharField(blank=True, help_text='Artisan stamp under base (e.g. initials or year)', max_length=30)),
                ('preview_data_url', models.TextField(blank=True, help_text='Base64 or canvas snapshot')),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atelier.ceramicshape')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('glaze', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atelier.glazeoption')),
            ],
        ),
    ]
